### ISSUE TITLE
I am unable to obtain the new ScanRefer dataset from the link you provided.

### ISSUE THREAD

**Issue by RobinLiuZX** [sosppxo/MDIN#1]
I am very interested in your work. Could you please provide a new download link?
![报错截图](https://github.com/user-attachments/assets/25bbdc98-3f74-4e62-856a-dcc4d11d2dea)

**Comment by Liuuuuuyh** [comment]
Thank you for your inquiry. We have updated the latest link, and you can now download the files through the link.



> I am very interested in your work. Could you please provide a new download link? ![报错截图](https://private-user-images.githubusercontent.com/80163805/354174556-25bbdc98-3f74-4e62-856a-dcc4d11d2dea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDcyNzYsIm5iZiI6MTcyMjUwNjk3NiwicGF0aCI6Ii84MDE2MzgwNS8zNTQxNzQ1NTYtMjViYmRjOTgtM2Y3NC00ZTYyLTg1NmEtZGNjNGQxMWQyZGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEwMDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZDg3NmU3ODgwZWFkMWY5ZDE0OTFiYmFlMzVjNDAyNWQyMzQ1NGNjMjM3Y2RmMmJjMDVhMGNhN2E3ZjM4MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8iXmQQ61YRE7b8Zq7ymmfqK4Bnq7oDORJQ9II4W16VY)

Thank you for your inquiry. We have updated the latest link, and you can now download the files through the link.

**Comment by Liuuuuuyh** [comment]
> I am very interested in your work. Could you please provide a new download link? ![报错截图](https://private-user-images.githubusercontent.com/80163805/354174556-25bbdc98-3f74-4e62-856a-dcc4d11d2dea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDczMTIsIm5iZiI6MTcyMjUwNzAxMiwicGF0aCI6Ii84MDE2MzgwNS8zNTQxNzQ1NTYtMjViYmRjOTgtM2Y3NC00ZTYyLTg1NmEtZGNjNGQxMWQyZGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEwMTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZDM3MDgzZjkxMzg2ZjcwOWYyMTI2YjFhZjMwNzI1NmZlNDhlYWIzODFhMTk2N2IyNDFhZjRmYzkxNzU4MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CoXqdUE-bGUeA2sG18xU0quZOXoTjHEOUihUCmDCVQQ)

Thank you for your inquiry. We have updated the latest link, and you can now download the files through the link.

**Comment by Liuuuuuyh** [comment]
> I am very interested in your work. Could you please provide a new download link? ![报错截图](https://private-user-images.githubusercontent.com/80163805/354174556-25bbdc98-3f74-4e62-856a-dcc4d11d2dea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDczMzUsIm5iZiI6MTcyMjUwNzAzNSwicGF0aCI6Ii84MDE2MzgwNS8zNTQxNzQ1NTYtMjViYmRjOTgtM2Y3NC00ZTYyLTg1NmEtZGNjNGQxMWQyZGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEwMTAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZDQ2MzgyNTI5MDA5OGI4YzZmOGUzNzdlMWVkYjAxMWZhZDgwMWVjMmJhZTkwZTkyZmQyODQ2ZGVkYThjMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8T43bnacymlh8BgCxF1RUnMGCBQeJKF5hzKT2VOUyUs)

Thank you for your inquiry. We have updated the latest link, and you can now download the files through the link.  [Here](https://github.com/sosppxo/MDIN/blob/main/README.md### ScanRefer dataset)

**Comment by Liuuuuuyh** [comment]
> I am very interested in your work. Could you please provide a new download link? ![报错截图](https://private-user-images.githubusercontent.com/80163805/354174556-25bbdc98-3f74-4e62-856a-dcc4d11d2dea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDc2OTgsIm5iZiI6MTcyMjUwNzM5OCwicGF0aCI6Ii84MDE2MzgwNS8zNTQxNzQ1NTYtMjViYmRjOTgtM2Y3NC00ZTYyLTg1NmEtZGNjNGQxMWQyZGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDEwMTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYzVlMDZkY2VjZWUxOTdhOTM5NWJjMDBhNzBiYmM3MTRmNThmNTIxNDE3YzdjODQ5NjBkM2I5YWJlODViNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hfUaoUFqL8FOvn-rHuEE0e1C3_I4LlUV4JqvbJuQt-8)

Thank you for your inquiry. We have updated the latest link, and you can now download the files through the link.  [here](https://github.com/sosppxo/MDIN/tree/main?tab=readme-ov-file#scanrefer-dataset)

**Comment by RobinLiuZX** [comment]
I'm encountering a bug like this again, and I'm wondering if it might be due to missing part of the dataset?
![image](https://github.com/user-attachments/assets/cf1ef586-a589-4272-ae2f-f9557c8cccc3)

**Comment by Liuuuuuyh** [comment]
Based on the issue you encountered, I found an incorrect filename `*_refer_l2.pth` in `get_sp_filenames()` function. I have corrected it to `*_refer.pth`, which matches the `.pth` file obtained from [Scannet data Preparation](https://github.com/sosppxo/MDIN/tree/main#scannet-v2-dataset).

**Comment by RobinLiuZX** [comment]
Thank you very much for your reply!But I found another bug. When I tried to run **train_3dgres.py** and **train_3dres.py**, this error message appeared. Can you help me solve it?
![image](https://github.com/user-attachments/assets/299c87c5-a2f5-4367-abb6-386e1a25d0d0)
The value of the variable **graph_node** is a str when I debug.

> > I'm encountering a bug like this again, and I'm wondering if it might be due to missing part of the dataset? ![image](https://private-user-images.githubusercontent.com/80163805/354445201-cf1ef586-a589-4272-ae2f-f9557c8cccc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzY1MTMsIm5iZiI6MTcyMjU3NjIxMywicGF0aCI6Ii84MDE2MzgwNS8zNTQ0NDUyMDEtY2YxZWY1ODYtYTU4OS00MjcyLWFlMmYtZjk1NTdjOGNjY2MzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA1MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZjBiMzhlMWRjNDdlZjY3YTFiM2I4ODExZWM5OTdmMjgyNzZlMzQ0MDVkYWNkZWU5OWQ2M2E1Y2NmMjAxZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SgD1du33Y7TAbfE-pkoz9dc2s64cQjvIV2uPHLMqjdk)
> 
> Based on the issue you encountered, I found an incorrect filename `*_refer_l2.pth` in `get_sp_filenames()` function. I have corrected it to `*_refer.pth`, which matches the `.pth` file obtained from [Scannet data Preparation](https://github.com/sosppxo/MDIN/tree/main#scannet-v2-dataset).

**Comment by Liuuuuuyh** [comment]
> Thank you very much for your reply!But I found another bug. When I tried to run **train_3dgres.py** and **train_3dres.py**, this error message appeared. Can you help me solve it? ![image](https://private-user-images.githubusercontent.com/80163805/354513078-299c87c5-a2f5-4367-abb6-386e1a25d0d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDkzMjYsIm5iZiI6MTcyMjYwOTAyNiwicGF0aCI6Ii84MDE2MzgwNS8zNTQ1MTMwNzgtMjk5Yzg3YzUtYTJmNS00MzY3LWFiYjYtMzg2ZTFhMjVkMGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE0MzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZTFkNmU4YTQ2NTE5NDgxZWRlY2UwMGQ3MDM2MjMwNTkyNTM1YTVmNjlkYTEwMjhjZDAwZDA1YmI1NGE2YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DHkUpDfUaUOEGfbrpuKiWZ5NcnDbzmO_EGAKB2tZ_XQ) The value of the variable **graph_node** is a str when I debug.

This issue likely occurs during sentence parsing, where errors in the nr3d dataset do not align with the ScanRefer data. I have revised the code `gres_model/dataset/scannetv2_3dgres.py` so that when parsing ScanRefer, unnecessary error corrections are avoided.

**Comment by RobinLiuZX** [comment]
Sorry, this bug still exists. I personally feel that there is no corresponding "node_id" attribute in the graph_node[0] variable. Please help!

**Comment by Liuuuuuyh** [comment]
> Sorry, this bug still exists. I personally feel that there is no corresponding "node_id" attribute in the graph_node[0] variable. Please help!

I suspect the issue lies with the `sng_parser`. We provided a link to the original `sng_parser`, but the version we are using has been modified through [EDA](https://github.com/yanmin-wu/EDA). The code for the` sng_parser` we use has already been uploaded.

**Comment by RobinLiuZX** [comment]
> > Sorry, this bug still exists. I personally feel that there is no corresponding "node_id" attribute in the graph_node[0] variable. Please help!
> 
> I suspect the issue lies with the `sng_parser`. We provided a link to the original `sng_parser`, but the version we are using has been modified through [EDA](https://github.com/yanmin-wu/EDA). The code for the `sng_parser` we use has already been uploaded.

Thank you for your help, now this open source work works! By the way, this open source work also needs to add some configuration files, which come from the open source work **EDA** and **3D-STMN**, as shown below:
![1722751228777](https://github.com/user-attachments/assets/af04b010-27fe-4ba8-a25d-51444bd938f9)
![image](https://github.com/user-attachments/assets/1b62adbb-bd92-497a-a3ff-8645ef3e858e)

**Comment by Starboy-at-earth** [comment]
How can you download scannetv2, 1.2t in total? I am stunned by the size.
